language: node_js
sudo: false
node_js:
- lts/*
after_success:
- npm run coveralls
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: Nikolaos.Georgiou@gmail.com
  api_key:
    secure: Dt+dxMC4LIM4tmz9b/dy6o5M1bc4r+h2Dfxts7wLQt1je71pH61XKLzyGSDiobkEd5svQxseKEzF+gxgfDOLHW2EQY41Mh9Xf8KkfBGCfbWllQAk60ymXU/CSzIoRyVLLnXggi4S6dupEpR5WBEfYWCnhVviEWyddX0MePMJ2bGU/yXKvXz29F+xKK4UxWPKUee/BsBnRoI+CmJrRwIP8izggRiAYWgohT0ViPcx9p7o9t76FQQwq0E9NDqGhn4qxohJ9EQi8W6z2E6Ry8luFDD8MUOo2MG4zXSIstMtszIOc3SwQBWTAmY0MJuhpOpZo54uCm/+0ectzSbXMr+gmfh/oQl1z82IYOCGgqiM6TIMcvr5zKFJ/ya4m5zsZ2gSu7z13rmKQLq0jBDSjmbnwYGOOcStP5ISnJD8z//BaC+4LKliRFcQZ0I3xzvb+SVppgAqylZWAMRH9TjAQgrs1naCmR1yVf7XKYuRurwWDQ/UZot9v3Xsvlu52eZJj2pf7FrkBuEm37LDn9R3VQx17j374v7nySlN0hTEfv+ewKAxRLdoAXiyXGeB6bydRMkF1UgNjfbObMZfddkVvdW2DQ5UassoUnQoS67ljfeo7M6tsqg/n73K1Js8VaLJpxiJt0Pua6d4v4ufJtgiKP8cPE1Y139aEzRZH6fFCzZcepI=
  on:
    tags: true
    repo: ngeor/yart
