language: go
script:
- go test ./...
- go build
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: v3lEaNBFxagRADJnEJazO1CFUw7tJLSX6L32lkG1caFfs95krSNMRcgnBzWSUQE9TqLrO6CO06UClXQSZfJGUlriVXS33MqgXIxmtNAQxo9A8LJsdNU90jOxuBsvkeJ+LA1R9JF6Wg+2wopPepvILaphPgvGdNJ3KsLqnzRc74n/NSVTKoSAIog8wWLAl73B6p9z8UUYSGyeDfstQXOxyCCrHkbfbvTPJ/kDRrdQYT0e8ibFHsqMSCCyaloTFzQ3DqUkZ8b7S93JoIUKWtUu71qsyV06ASudE7LEs1NLxfIA2iTR4slg/GuCLuu2AQu2T10JThke2RJAFS17AlI5D4uGlThyyHFkv2zxlJ1/kRaDCi9lZIC0ogXc8dYZ71vtqkt+O6vyiQgeV6VqzIVsBetV1D6HbCk07eoR+k5Fq8yi9kcJkoBPHX7elqSXj0fEA7RAuPNOtKKTELTrtF4cw1jEYqt/RNwyR3X9IZTDdncSontlMnNPq/NQot1L6wGfWB4hWDZ+XOcG++m4Q6sa/BA3J6u2St3lk09oP27ISqJAuUvFfW4H7eexGz/JyUT2lqR6z0GIrz5s3LDjSH4kOADBFCF+CgSOVsTSprsDpCSM9DrDEvv/WzXtUToLQscwKQPv9IqDCbje6jpY0CSXG87GPSKZw9yk0sW4ZM7R13M=
  file: yart
  on:
    repo: ngeor/yart
    tags: true
