language: node_js
sudo: false
node_js:
  - lts/*
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run typedoc
  - npm pack
  - npm link
  - yart --version
after_success:
  - npm run coveralls
deploy:
  skip_cleanup: true
  provider: npm
  email: Nikolaos.Georgiou@gmail.com
  api_key:
    secure: O7OOfm2j1msl9g4qHwJBBrZ92RRVtZk+Np+xTx0tKqJmsSjbojZ9mLVhd9dzPQjwjW6kQCyqmU5JN92StImUZ32J1yb1EN4WSx5T7QzHtrPWTGaoyTj6YMt2d2noXpU+m9KtPoyHAE7D6WHqG60m8IbaE/egMSunO/bQI5PtPQgn84l9YYWjSYY5PPuts9hvjCpS6I3YZIcaGY4zYvYB37pxahjg/EVljoL+Dc22KuQu+kqg6J1RVHyJasGsLJnKV/i74eOMERDJH3FwYqW5Mf23aa3YyA3n4oA+NeZJGqjQEVfig4Q849cCLiqK5ADQzkHFm4nco1RJ4dSJ7O23BnX2ODq9rvpIfUDF9b1+TJmYi/fzNCCL+Qb4FE+rbidl7YH7p9zTY7UIGHQnB6+igFsiCHdDY2hYgHENyDlUfa/oI3d98f0Hv+IXbrBVkl8ICYqEzbGGlu6u9PqcV1PyoAvJzSb4uWOe+Xw7xwxym168NfO4X23fKZiOEN4/rZ+ghuu2be4UlFqC7wHYrzjXffy1L1bH0RpE4/7KcnbXOOy3OBIXRX8UutTEz2p8OCvpQVAx22k1Oui7NRB6IHDdlokwd52YjomdYunJikxEW9fwxU4jznvP4thHTBw7UNtOSopkhb3yOdljVMQH8aXiXRNtXnvtk0lTEO1Yl9u2w70=
  on:
    tags: true
    repo: ngeor/yart
