version: "{build}"

build: off

clone_folder: c:\gopath\src\github.com\ngeor\yart

environment:
  GOPATH: c:\gopath

stack: go 1.10

before_test:
- go vet ./...

test_script:
- go test -v ./...
- go build

artifacts:
- path: yart.exe
  name: yart.exe

deploy:
  provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_REPO_TAG_NAME)
  artifact: yart.exe
  auth_token:
    secure: N+BZDjoKy1FxA8vuKILBLoWdLUnAlXfuv0GInzDhBzwJTsqj08iwq95f/goqGjZz
  on:
    APPVEYOR_REPO_TAG: true
